CREATE OR REPLACE FUNCTION get_id(
  XIDENT IN VARCHAR,
  XPWD IN VARCHAR
) RETURN INTEGER
AS
id INTEGER;
BEGIN
  SELECT id_personne INTO id FROM personnes WHERE IDENT=XIDENT and PASSWD=XPWD;
  RETURN id;
  EXCEPTION
    WHEN no_data_found THEN
      RETURN 0;
END;