CREATE PROCEDURE inscrire(
  NOM IN VARCHAR,
  XPRENOM IN VARCHAR,
  XIDENT IN VARCHAR,
  XPWD IN VARCHAR
) AS BEGIN
INSERT INTO personnes VALUES (((SELECT MAX(id_personnes) FROM personnes)+1), NOM, XPRENOM, XPWD, XIDENT);
COMMIT;
END;

GRANT EXECUTE ON inscrire TO deniauh1;

